// <auto-generated />
#nullable enable

using System;

namespace CarpaNet.Validation;

/// <summary>
/// Validates that a string or byte array length is within the specified range.
/// AOT-safe replacement for System.ComponentModel.DataAnnotations.StringLengthAttribute.
/// </summary>
[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter, AllowMultiple = false)]
public sealed class ATStringLengthAttribute : Attribute
{
    public int MaximumLength { get; }
    public int MinimumLength { get; set; }

    public ATStringLengthAttribute(int maximumLength)
    {
        MaximumLength = maximumLength;
    }

    public bool IsValid(string? value)
    {
        if (value == null) return true;
        return value.Length >= MinimumLength && value.Length <= MaximumLength;
    }
}

/// <summary>
/// Validates that a collection or string does not exceed a maximum length.
/// AOT-safe replacement for System.ComponentModel.DataAnnotations.MaxLengthAttribute.
/// </summary>
[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter, AllowMultiple = false)]
public sealed class ATMaxLengthAttribute : Attribute
{
    public int Length { get; }

    public ATMaxLengthAttribute(int length)
    {
        Length = length;
    }
}

/// <summary>
/// Validates that a collection or string meets a minimum length.
/// AOT-safe replacement for System.ComponentModel.DataAnnotations.MinLengthAttribute.
/// </summary>
[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter, AllowMultiple = false)]
public sealed class ATMinLengthAttribute : Attribute
{
    public int Length { get; }

    public ATMinLengthAttribute(int length)
    {
        Length = length;
    }
}

/// <summary>
/// Validates that a numeric value (long) is within the specified range.
/// AOT-safe replacement for System.ComponentModel.DataAnnotations.RangeAttribute(Type, String, String).
/// </summary>
[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter, AllowMultiple = false)]
public sealed class ATRangeAttribute : Attribute
{
    public long Minimum { get; }
    public long Maximum { get; }

    public ATRangeAttribute(long minimum, long maximum)
    {
        Minimum = minimum;
        Maximum = maximum;
    }

    public bool IsValid(long value)
    {
        return value >= Minimum && value <= Maximum;
    }
}
