// <auto-generated />
#nullable enable

using System.Threading;
using System.Threading.Tasks;

namespace CarpaNet.Identity;

/// <summary>
/// Interface for caching identity resolution results.
/// </summary>
public interface IIdentityCache
{
    /// <summary>
    /// Gets a cached DID document by DID.
    /// </summary>
    /// <param name="did">The DID to look up.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The cached DID document, or null if not found or expired.</returns>
    Task<DidDocument?> GetDidDocumentAsync(string did, CancellationToken cancellationToken = default);

    /// <summary>
    /// Caches a DID document.
    /// </summary>
    /// <param name="did">The DID key.</param>
    /// <param name="document">The DID document to cache.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task SetDidDocumentAsync(string did, DidDocument document, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets a cached DID for a handle.
    /// </summary>
    /// <param name="handle">The handle to look up.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The cached DID, or null if not found or expired.</returns>
    Task<string?> GetHandleDidAsync(string handle, CancellationToken cancellationToken = default);

    /// <summary>
    /// Caches a handle-to-DID mapping.
    /// </summary>
    /// <param name="handle">The handle key.</param>
    /// <param name="did">The DID to cache.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task SetHandleDidAsync(string handle, string did, CancellationToken cancellationToken = default);

    /// <summary>
    /// Removes a DID document from the cache.
    /// </summary>
    /// <param name="did">The DID to remove.</param>
    void RemoveDidDocument(string did);

    /// <summary>
    /// Removes a handle-to-DID mapping from the cache.
    /// </summary>
    /// <param name="handle">The handle to remove.</param>
    void RemoveHandle(string handle);

    /// <summary>
    /// Clears all cached entries.
    /// </summary>
    void Clear();
}
