// <auto-generated />
#nullable enable

using System;
using System.Collections.Concurrent;
using System.Threading;
using System.Threading.Tasks;

namespace CarpaNet.Identity;

/// <summary>
/// In-memory implementation of <see cref="IIdentityCache"/> with TTL and size limits.
/// </summary>
public sealed class MemoryIdentityCache : IIdentityCache
{
    private readonly ConcurrentDictionary<string, CacheEntry<DidDocument>> _didDocuments = new();
    private readonly ConcurrentDictionary<string, CacheEntry<string>> _handleDids = new();
    private readonly TimeSpan _didDocumentTtl;
    private readonly TimeSpan _handleTtl;
    private readonly int _maxEntries;

    private sealed class CacheEntry<T>
    {
        public CacheEntry(T value, DateTimeOffset expiresAt)
        {
            Value = value;
            ExpiresAt = expiresAt;
        }

        public T Value { get; }
        public DateTimeOffset ExpiresAt { get; }
        public bool IsExpired => DateTimeOffset.UtcNow >= ExpiresAt;
    }

    /// <summary>
    /// Default TTL for DID documents (5 minutes).
    /// </summary>
    public static readonly TimeSpan DefaultDidDocumentTtl = TimeSpan.FromMinutes(5);

    /// <summary>
    /// Default TTL for handle-to-DID mappings (2 minutes).
    /// Handle mappings have shorter TTL since they can change more frequently.
    /// </summary>
    public static readonly TimeSpan DefaultHandleTtl = TimeSpan.FromMinutes(2);

    /// <summary>
    /// Default maximum number of entries per cache type.
    /// </summary>
    public const int DefaultMaxEntries = 1000;

    /// <summary>
    /// Creates a new in-memory identity cache with default settings.
    /// </summary>
    public MemoryIdentityCache()
        : this(DefaultDidDocumentTtl, DefaultHandleTtl, DefaultMaxEntries)
    {
    }

    /// <summary>
    /// Creates a new in-memory identity cache with custom settings.
    /// </summary>
    /// <param name="didDocumentTtl">TTL for cached DID documents.</param>
    /// <param name="handleTtl">TTL for cached handle-to-DID mappings.</param>
    /// <param name="maxEntries">Maximum number of entries per cache type.</param>
    public MemoryIdentityCache(TimeSpan didDocumentTtl, TimeSpan handleTtl, int maxEntries = DefaultMaxEntries)
    {
        if (didDocumentTtl <= TimeSpan.Zero)
            throw new ArgumentException("TTL must be positive", nameof(didDocumentTtl));
        if (handleTtl <= TimeSpan.Zero)
            throw new ArgumentException("TTL must be positive", nameof(handleTtl));
        if (maxEntries <= 0)
            throw new ArgumentException("Max entries must be positive", nameof(maxEntries));

        _didDocumentTtl = didDocumentTtl;
        _handleTtl = handleTtl;
        _maxEntries = maxEntries;
    }

    /// <summary>
    /// Gets the TTL for DID documents.
    /// </summary>
    public TimeSpan DidDocumentTtl => _didDocumentTtl;

    /// <summary>
    /// Gets the TTL for handle-to-DID mappings.
    /// </summary>
    public TimeSpan HandleTtl => _handleTtl;

    /// <summary>
    /// Gets the maximum number of entries per cache type.
    /// </summary>
    public int MaxEntries => _maxEntries;

    /// <summary>
    /// Gets the current number of cached DID documents.
    /// </summary>
    public int DidDocumentCount => _didDocuments.Count;

    /// <summary>
    /// Gets the current number of cached handle-to-DID mappings.
    /// </summary>
    public int HandleCount => _handleDids.Count;

    /// <inheritdoc/>
    public Task<DidDocument?> GetDidDocumentAsync(string did, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrEmpty(did))
            return Task.FromResult<DidDocument?>(null);

        var key = NormalizeKey(did);

        if (_didDocuments.TryGetValue(key, out var entry))
        {
            if (!entry.IsExpired)
            {
                return Task.FromResult<DidDocument?>(entry.Value);
            }

            // Remove expired entry
            _didDocuments.TryRemove(key, out _);
        }

        return Task.FromResult<DidDocument?>(null);
    }

    /// <inheritdoc/>
    public Task SetDidDocumentAsync(string did, DidDocument document, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrEmpty(did) || document == null)
            return Task.CompletedTask;

        var key = NormalizeKey(did);

        // Evict expired entries if we're at capacity
        if (_didDocuments.Count >= _maxEntries)
        {
            EvictExpiredEntries(_didDocuments);
        }

        _didDocuments[key] = new CacheEntry<DidDocument>(
            document,
            DateTimeOffset.UtcNow + _didDocumentTtl);

        return Task.CompletedTask;
    }

    /// <inheritdoc/>
    public Task<string?> GetHandleDidAsync(string handle, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrEmpty(handle))
            return Task.FromResult<string?>(null);

        var key = NormalizeKey(handle);

        if (_handleDids.TryGetValue(key, out var entry))
        {
            if (!entry.IsExpired)
            {
                return Task.FromResult<string?>(entry.Value);
            }

            // Remove expired entry
            _handleDids.TryRemove(key, out _);
        }

        return Task.FromResult<string?>(null);
    }

    /// <inheritdoc/>
    public Task SetHandleDidAsync(string handle, string did, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrEmpty(handle) || string.IsNullOrEmpty(did))
            return Task.CompletedTask;

        var key = NormalizeKey(handle);

        // Evict expired entries if we're at capacity
        if (_handleDids.Count >= _maxEntries)
        {
            EvictExpiredEntries(_handleDids);
        }

        _handleDids[key] = new CacheEntry<string>(
            did,
            DateTimeOffset.UtcNow + _handleTtl);

        return Task.CompletedTask;
    }

    /// <inheritdoc/>
    public void RemoveDidDocument(string did)
    {
        if (string.IsNullOrEmpty(did))
            return;

        var key = NormalizeKey(did);
        _didDocuments.TryRemove(key, out _);
    }

    /// <inheritdoc/>
    public void RemoveHandle(string handle)
    {
        if (string.IsNullOrEmpty(handle))
            return;

        var key = NormalizeKey(handle);
        _handleDids.TryRemove(key, out _);
    }

    /// <inheritdoc/>
    public void Clear()
    {
        _didDocuments.Clear();
        _handleDids.Clear();
    }

    /// <summary>
    /// Removes all expired entries from the cache.
    /// </summary>
    public void EvictExpired()
    {
        EvictExpiredEntries(_didDocuments);
        EvictExpiredEntries(_handleDids);
    }

    private static string NormalizeKey(string key)
    {
        return key.ToLowerInvariant().Trim();
    }

    private static void EvictExpiredEntries<T>(ConcurrentDictionary<string, CacheEntry<T>> cache)
    {
        foreach (var key in cache.Keys)
        {
            if (cache.TryGetValue(key, out var entry) && entry.IsExpired)
            {
                cache.TryRemove(key, out _);
            }
        }
    }
}
