// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Http;

namespace CarpaNet.AspNetCore;

/// <summary>
/// ATProtocol XRPC error result implementing <see cref="IResult"/>.
/// </summary>
public sealed class ATErrorResult : IResult
{
    /// <summary>
    /// Gets the HTTP status code.
    /// </summary>
    public int StatusCode { get; private init; }

    /// <summary>
    /// Gets the error type identifier.
    /// </summary>
    public string? Error { get; private init; }

    /// <summary>
    /// Gets the human-readable error message.
    /// </summary>
    public string? Message { get; private init; }

    /// <summary>
    /// Creates a Bad Request (400) error.
    /// </summary>
    public static ATErrorResult BadRequest(string? message = null)
        => new() { StatusCode = 400, Error = "BadRequest", Message = message ?? "Bad Request" };

    /// <summary>
    /// Creates an Unauthorized (401) error.
    /// </summary>
    public static ATErrorResult Unauthorized(string? message = null)
        => new() { StatusCode = 401, Error = "AuthMissing", Message = message ?? "Authentication Required" };

    /// <summary>
    /// Creates a Forbidden (403) error.
    /// </summary>
    public static ATErrorResult Forbidden(string? message = null)
        => new() { StatusCode = 403, Error = "Forbidden", Message = message ?? "Forbidden" };

    /// <summary>
    /// Creates a Not Found (404) error.
    /// </summary>
    public static ATErrorResult NotFound(string? message = null)
        => new() { StatusCode = 404, Error = "NotFound", Message = message ?? "Not Found" };

    /// <summary>
    /// Creates a Payload Too Large (413) error.
    /// </summary>
    public static ATErrorResult PayloadTooLarge(string? message = null)
        => new() { StatusCode = 413, Error = "PayloadTooLarge", Message = message ?? "Payload Too Large" };

    /// <summary>
    /// Creates a Too Many Requests (429) error.
    /// </summary>
    public static ATErrorResult TooManyRequests(string? message = null)
        => new() { StatusCode = 429, Error = "TooManyRequests", Message = message ?? "Too Many Requests" };

    /// <summary>
    /// Creates an Internal Server Error (500) error.
    /// </summary>
    public static ATErrorResult InternalServerError(string? message = null)
        => new() { StatusCode = 500, Error = "InternalServerError", Message = message ?? "Internal Server Error" };

    /// <summary>
    /// Creates an Internal Server Error (500) from an exception.
    /// </summary>
    public static ATErrorResult InternalServerError(Exception exception)
        => new() { StatusCode = 500, Error = "InternalServerError", Message = exception.Message };

    /// <summary>
    /// Creates a Not Implemented (501) error.
    /// </summary>
    public static ATErrorResult NotImplemented(string? message = null)
        => new() { StatusCode = 501, Error = "NotImplemented", Message = message ?? "Not Implemented" };

    /// <summary>
    /// Creates a Bad Gateway (502) error.
    /// </summary>
    public static ATErrorResult BadGateway(string? message = null)
        => new() { StatusCode = 502, Error = "BadGateway", Message = message ?? "Bad Gateway" };

    /// <summary>
    /// Creates a Service Unavailable (503) error.
    /// </summary>
    public static ATErrorResult ServiceUnavailable(string? message = null)
        => new() { StatusCode = 503, Error = "ServiceUnavailable", Message = message ?? "Service Unavailable" };

    /// <summary>
    /// Creates a Gateway Timeout (504) error.
    /// </summary>
    public static ATErrorResult GatewayTimeout(string? message = null)
        => new() { StatusCode = 504, Error = "GatewayTimeout", Message = message ?? "Gateway Timeout" };

    /// <inheritdoc/>
    public Task ExecuteAsync(HttpContext httpContext)
    {
        httpContext.Response.StatusCode = StatusCode;
        httpContext.Response.ContentType = "application/json";
        var error = new XrpcError
        {
            Error = this.Error,
            Message = this.Message,
        };
        return httpContext.Response.WriteAsync(error.ToJson());
    }
}
