// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;

namespace CarpaNet.AspNetCore;

/// <summary>
/// ATProtocol XRPC error response body.
/// </summary>
public sealed class XrpcError
{
    /// <summary>
    /// Gets the error type identifier.
    /// </summary>
    [JsonPropertyName("error")]
    public string? Error { get; init; }

    /// <summary>
    /// Gets the human-readable error message.
    /// </summary>
    [JsonPropertyName("message")]
    public string? Message { get; init; }

    /// <summary>
    /// Serializes this error to a JSON string.
    /// </summary>
    public string ToJson()
    {
        return JsonSerializer.Serialize(this, XrpcJsonContext.Default.XrpcError);
    }
}
