// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace CarpaNet.AspNetCore;

[JsonSerializable(typeof(XrpcError))]
internal sealed partial class XrpcJsonContext : JsonSerializerContext
{
}
